platform:ios,'8.0'
target 'ZhongBao' do

pod 'Masonry'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'CocoaSecurity'
pod 'SDCycleScrollView'

end
